ResumeBank.Web/Controllers/CandidateController.cs
using PagedList;
using ResumeBank.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;

namespace ResumeBank.Web.Controllers
{
    [Authorize]
    public class CandidateController : Controller
    {
        private CandidateModel _candidateModel;

        public CandidateController()
        {
            _candidateModel = new CandidateModel();
        }

        // GET: Candidate
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        // Add new Candidate
        public ActionResult AddCandidate(int? id)
        {
            if (id != null)
            {
                _candidateModel = new CandidateModel(id);
            }
            return View(_candidateModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddCandidate(CandidateModel candidateModel)
        {

            if(ModelState.IsValid)
            {
                if (candidateModel.Id != 0 && candidateModel.Id  != null)
                {
                    candidateModel.UpdateCandidate();
                    TempData["notifyMessage"] = "<script>$.notify('Succesfully Updated', 'success');</script>";
                    return RedirectToAction("Search");
                }
                else
                {
                    candidateModel.AddCandidate();
                    TempData["notifyMessage"] = "<script>$.notify('Succesfully Added', 'success');</script>";
                    return RedirectToAction("AddCandidate");
                }  
            }

            TempData["notifyMessage"] = "<script>$.notify('Failed', 'error');</script>";
            return View(candidateModel);
        }

        [HttpGet]
        public ActionResult Search(CandidateModel candidateModel)
        {
            candidateModel = candidateModel != null ? candidateModel : new CandidateModel();
            candidateModel.SetAllCandidatesBySearchWithPaging();
            return View(candidateModel);
        }

        public ActionResult DeleteCandidate(int id)
        {
            var isDeleted = _candidateModel.DeleteCandidateById(id);
            if (isDeleted)
                TempData["notifyMessage"] = "<script>$.notify('Succesfully Deleted', 'success');</script>";
            return Json(isDeleted, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetSubCategories(int id)
        {
            var subCategory = _candidateModel.GetSubCategories(id);
            return Json(subCategory, JsonRequestBehavior.AllowGet);
        }

    }
}

ResumeBank.Web/Views/Candidate/AddCandidate.cshtml
@model ResumeBank.Web.Models.CandidateModel
@{
    ViewBag.Title = "AddCandidate";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{ var newOrUpdate = "New"; }

@if (Model.Id != null && Model.Id != 0)
{
    newOrUpdate = "Update";
}

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Candidate
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Candidate</a></li>
        <li class="active">@newOrUpdate Candidate</li>
    </ol>
</section>


<!-- Main content -->
@using (Html.BeginForm("AddCandidate", "Candidate", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.OriginalResumeId)
    @Html.HiddenFor(model => model.ModifiedResumeId)
    <section class="content">
        <div class="box box-default">
            <div class="box-header with-border">
                <h3 class="box-title">@newOrUpdate Candidate</h3>
            </div>
            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="box-body">
                    <div class="form-group">
                        @Html.LabelFor(c => c.Name, new { @class = "col-sm-2 control-label" })
                        <div class="col-sm-6">
                            @Html.TextBoxFor(c => c.Name, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(c => c.Email, new { @class = "col-sm-2 control-label" })
                        <div class="col-sm-6">
                            @Html.TextBoxFor(c => c.Email, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(c => c.Phone, new { @class = "col-sm-2 control-label" })
                        <div class="col-sm-6">
                            @Html.TextBoxFor(c => c.Phone, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(c => c.Address, new { @class = "col-sm-2 control-label" })
                        <div class="col-sm-6">
                            @Html.TextBoxFor(c => c.Address, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(c => c.DateOfBirth, new { @class = "col-sm-2 control-label" })
                        <div class="col-sm-6">
                            @Html.TextBoxFor(c => c.DateOfBirth, "{0:MM/dd/yyyy}", new { @class = "form-control datemask", @placeholder = "mm/dd/yyyy" })
                            @Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(c => c.GenderId, new { @class = "col-sm-2 control-label" })
                        <div class="col-sm-6">
                            @Html.DropDownListFor(c => c.GenderId, new SelectList(Model.Genders, "Id", "Name"), "---Select---", new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.GenderId, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(c => c.JobLevelId, new { @class = "col-sm-2 control-label" })
                        <div class="col-sm-6">
                            @Html.DropDownListFor(c => c.JobLevelId, new SelectList(Model.JobLevels, "Id", "Name"), "---Select---", new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.JobLevelId, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(c => c.PrimaryCategoryId, new { @class = "col-sm-2 control-label" })
                        <div class="col-sm-6">
                            @Html.DropDownListFor(c => c.PrimaryCategoryId, new SelectList(Model.PrimaryCategories, "Id", "Name"), "---Select---", new { @class = "form-control", @id="primaryCategoryId" })
                            @Html.ValidationMessageFor(model => model.PrimaryCategoryId, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(c => c.SubCategorySelectedIds, new { @class = "col-sm-2 control-label" })
                        <div class="col-sm-6">
                            @Html.ListBoxFor(c => c.SubCategorySelectedIds, new MultiSelectList(Model.SubCategories, "Id", "Name", @Model.SubCategorySelectedIds), new { @class = "form-control select2", @id = "subCategoryId", @disabled = true })
                            @Html.ValidationMessageFor(model => model.SubCategorySelectedIds, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(c => c.EducationLevelId, new { @class = "col-sm-2 control-label" })
                        <div class="col-sm-6">
                            @Html.DropDownListFor(c => c.EducationLevelId, new SelectList(Model.EducationLevels, "Id", "Name"), "---Select---", new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.EducationLevelId, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(c => c.SubjectId, new { @class = "col-sm-2 control-label" })
                        <div class="col-sm-6">
                            @Html.DropDownListFor(c => c.SubjectId, new SelectList(Model.Subjects, "Id", "Name"), "---Select---", new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.SubjectId, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(c => c.InstituteId, new { @class = "col-sm-2 control-label" })
                        <div class="col-sm-6">
                            @Html.DropDownListFor(c => c.InstituteId, new SelectList(Model.Institutes, "Id", "Name"), "---Select---", new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.InstituteId, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(c => c.Training, new { @class = "col-sm-2 control-label" })
                        <div class="col-sm-6">
                            @Html.TextAreaFor(c => c.Training, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Training, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(c => c.TotalExperience, new { @class = "col-sm-2 control-label" })
                        <div class="col-sm-6">
                            @Html.TextBoxFor(c => c.TotalExperience, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.TotalExperience, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(c => c.CurrentSalary, new { @class = "col-sm-2 control-label" })
                        <div class="col-sm-6">
                            @Html.TextBoxFor(c => c.CurrentSalary, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.CurrentSalary, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(c => c.ExpectedSalary, new { @class = "col-sm-2 control-label" })
                        <div class="col-sm-6">
                            @Html.TextBoxFor(c => c.ExpectedSalary, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.ExpectedSalary, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(c => c.Keywords, new { @class = "col-sm-2 control-label" })
                        <div class="col-sm-6">
                            @Html.TextBoxFor(c => c.Keywords, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Keywords, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    @if (Model.Id != null && Model.Id != 0)
                    {
                        
                        <div class="form-group">
                            @Html.Label("Original Resume File", new { @class = "col-sm-2 control-label" })
                            <div class="col-sm-6">
                                @if (Model.OriginalResume != null)
                                {
                                    <a href="@Url.Content(Model.OriginalResume.Url)" target="_blank">
                                        <img src="@(Model.OriginalResume.Url.EndsWith(".pdf") ? "/Content/img/pdf-icon.png" :
                                            Model.OriginalResume.Url.EndsWith(".doc") || Model.OriginalResume.Url.EndsWith(".docx") ? "/Content/img/doc-icon.png" :
                                            "/Content/img/ppt-icon.png")" width="50px" height="50px" />
                                    </a>
                                }
                                else
                                {
                                    <label class="control-label">No File</label>
                                }
                            </div>
                        </div>
                        
                        <div class="form-group">
                            @Html.Label("Modified Resume File", new { @class = "col-sm-2 control-label" })
                            <div class="col-sm-6">
                                @if (Model.ModifiedResume != null)
                                {
                                    <a href="@Url.Content(Model.ModifiedResume.Url)" target="_blank">
                                        <img src="@(Model.ModifiedResume.Url.EndsWith(".pdf") ? "/Content/img/pdf-icon.png" :
                                            Model.ModifiedResume.Url.EndsWith(".doc") || Model.ModifiedResume.Url.EndsWith(".docx") ? "/Content/img/doc-icon.png" :
                                            "/Content/img/ppt-icon.png")" width="50px" height="50px" />
                                    </a>
                                }
                                else
                                {
                                    <label class="control-label">No File</label>
                                }
                            </div>
                        </div>
                        
                    }
                    <div class="form-group">
                        <label for="originalResumeFile" class="col-sm-2 control-label">Original Resume</label>
                        <div class="col-sm-6">
                            <input type="file" id="originalResumeFile" name="OriginalResumeFile">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="modifiedResumeFile" class="col-sm-2 control-label">Modified Resume</label>
                        <div class="col-sm-6">
                            <input type="file" id="modifiedResumeFile" name="ModifiedResumeFile">
                        </div>
                    </div>
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    <button type="button" class="btn btn-default" onclick="window.location.reload(true)">Cancel</button>
                    <button type="submit" class="btn btn-info pull-right">Save</button>
                </div>
                <!-- /.box-footer -->
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </section>
    <!-- /.content -->
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/Project/candidate.js"></script>
}

ResumeBank.Web/Views/Candidate/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

ResumeBank.Web/Views/Candidate/Search.cshtml
@model ResumeBank.Web.Models.CandidateModel
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    ViewBag.Title = "Search";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Candidate Search
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Candidate</a></li>
        <li class="active">Search</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="col-sm-12">
        <div class="box box-default">
            <div class="box-header with-border">
                <h3 class="box-title">Search Criteria</h3>
            </div>
            @using (Html.BeginForm("Search", "Candidate", FormMethod.Get))
            {
                <div class="form-horizontal">
                    <div class="box-body">
                        <div class="form-group col-sm-3">
                            <div class="col-sm-12">
                                @Html.TextBoxFor(c => c.Keywords, new { @class = "form-control", @placeholder = "Keyword" })
                            </div>
                        </div>
                        <div class="form-group col-sm-3">
                            <div class="col-sm-12">
                                @Html.DropDownListFor(c => c.PrimaryCategoryId, new SelectList(Model.PrimaryCategories, "Id", "Name"), "---Select Category---", new { @class = "form-control", @id = "primaryCategorySearchId" })
                            </div>
                        </div>
                        <div class="form-group col-sm-3">
                            <div class="col-sm-12">
                                @Html.DropDownListFor(c => c.SubCategoryId, new SelectList(Model.SubCategories, "Id", "Name"), "---Select Sub-Category---", new { @class = "form-control", @id = "subCategorySearchId", @disabled = true })
                            </div>
                        </div>
                        <div class="form-group col-sm-3">
                            <div class="col-sm-12">
                                @Html.DropDownListFor(c => c.EducationLevelId, new SelectList(Model.EducationLevels, "Id", "Name"), "---Select Education Level---", new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group col-sm-3">
                            <div class="col-sm-12">
                                @Html.DropDownListFor(c => c.SubjectId, new SelectList(Model.Subjects, "Id", "Name"), "---Select Subject---", new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group col-sm-3">
                            <div class="col-sm-12">
                                @Html.DropDownListFor(c => c.InstituteId, new SelectList(Model.Institutes, "Id", "Name"), "---Select Institute---", new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group col-sm-3">
                            <div class="col-sm-12">
                                @Html.DropDownListFor(c => c.JobLevelId, new SelectList(Model.JobLevels, "Id", "Name"), "---Select Job Level---", new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group col-sm-3">
                            <div class="col-sm-12">
                                @Html.TextBoxFor(c => c.Training, new { @class = "form-control", @placeholder = "Training" })
                            </div>
                        </div>
                        <div class="form-group col-sm-3">
                            <div class="col-sm-12">
                                @Html.TextBoxFor(c => c.TotalExperience, new { @class = "form-control", @placeholder = "Total Experience" })
                            </div>
                        </div>
                        <div class="form-group col-sm-3">
                            <div class="col-sm-12">
                                @Html.TextBoxFor(c => c.CurrentSalary, new { @class = "form-control", @placeholder = "Current Salary" })
                            </div>
                        </div>
                        <div class="form-group col-sm-3">
                            <div class="col-sm-12">
                                @Html.TextBoxFor(c => c.ExpectedSalary, new { @class = "form-control", @placeholder = "Expected Salary" })
                            </div>
                        </div>
                        <div class="form-group col-sm-3">
                            <div class="col-sm-12">
                                <button type="submit" class="btn btn-info btn-block">Search</button>
                            </div>
                        </div>
                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer">

                    </div>
                    <!-- /.box-footer -->
                </div>
            }
            <!-- /.box-body -->
        </div>
    </div>

    <div class="col-sm-12">
        <div class="box box-default">
            <div class="box-header with-border">
                <h3 class="box-title">Total @Model.CandidatesPagedList.TotalItemCount @(Model.CandidatesPagedList.TotalItemCount > 1 ? "Candidates" : "Candidate")</h3>
            </div>
            <div class="box-body">
                <table id="example1" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Category</th>
                            <th>Institution</th>
                            <th>Expected Salary</th>
                            <th>Experience (yr)</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var candidate in Model.CandidatesPagedList)
                        {
                            var instName = candidate.Institute != null ? candidate.Institute.Name : "";
                            <tr>
                                <td>@candidate.Name</td>
                                <td>@candidate.PrimaryCategory.Name</td>
                                <td>@instName</td>
                                <td>@candidate.ExpectedSalary</td>
                                <td>@candidate.TotalExperience</td>
                                <td>
                                    <a class="btn btn-success btn-sm"
                                       href='@Url.Action("AddCandidate", "Candidate", new {id = candidate.Id})'>
                                        <i class="fa fa-pencil"></i>
                                    </a>
                                    <a class="btn btn-danger btn-sm"
                                       href='' onclick="ConfirmDeleteCandidate(@candidate.Id)" data-toggle="modal">
                                        <i class="fa fa-remove"></i>
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <!-- /.box-body -->
            <div class="box-footer">
                <div class="pull-left">
                    Page @(Model.CandidatesPagedList.PageCount < Model.CandidatesPagedList.PageNumber ? 0 : Model.CandidatesPagedList.PageNumber)
                    of @Model.CandidatesPagedList.PageCount
                </div>
                <div class="pull-right">
                    @Html.PagedListPager(Model.CandidatesPagedList, page =>
                        {
                            Model.PageNumber = page;
                            return Url.Action("Search", "Candidate", new
                            {
                                Model.Keywords,
                                Model.PrimaryCategoryId,
                                Model.SubCategoryId,
                                Model.EducationLevelId,
                                Model.SubjectId,
                                Model.InstituteId,
                                Model.JobLevelId,
                                Model.Training,
                                Model.TotalExperience,
                                Model.CurrentSalary,
                                Model.ExpectedSalary,
                                Model.PageNumber

                            });
                        })
                </div>
            </div>
            <!-- /.box-footer -->
            <!-- /.box-body -->
        </div>
    </div>

    <!-- /.box -->
</section>
<!-- /.content -->
<!-- Start Delete Modal -->
<div class="modal fade" id="confirmDeleteModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title text-center text-danger">Confirmation Message</h4>
            </div>
            <div class="modal-body text-center">
                <p>Are you sure want to delete this Candidate ?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" onclick="DeleteCandidate()">Confirm</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

<input type="hidden" id="hiddenCandidateId" />

@section scripts{
    <script src="~/Scripts/Project/candidate.js"></script>
}